Repository finleap-connect/monoskope, pull requests merged in 2022-03, with the labels that each got.

#71 ADR for secret management in Monoskope
  docs/architecture-decisions/ADR-3-secret-management.md
Labels: documentation

#73 Remove changelog in favor of releases page
  CHANGELOG.md
Labels: bug, chore

#74 ADR secret management
  docs/architecture-decisions/ADR-3-secret-management.md
Labels: chore

#76 Add audit log service (getByDateRange)
  api/domain/audit/event.proto
  api/domain/queryhandler_service.proto
  build/package/helm/monoskope/templates/ambassador/mappings/queryhandler.yaml
  cmd/queryhandler/server.go
  internal/audit_log_test.go
  internal/integration_test.go
  internal/queryhandler/audit_log_server.go
  internal/queryhandler/testenv.go
  pkg/api/domain/audit/event.pb.go
  pkg/api/domain/audit/event.pb.validate.go
  pkg/api/domain/queryhandler_service.pb.go
  pkg/api/domain/queryhandler_service.pb.validate.go
  pkg/api/domain/queryhandler_service_grpc.pb.go
  pkg/audit/audit_formatter.go
  pkg/audit/errors/errors.go
  pkg/audit/eventformatter/event_formatter.go
  pkg/audit/eventformatter/event_formatter_registry.go
  pkg/audit/eventformatter/event_formatter_registry_test.go
  pkg/audit/eventformatter/suite_test.go
  pkg/domain/constants/events/events.go
  pkg/domain/formatters/events/certificate.go
  pkg/domain/formatters/events/cluster.go
  pkg/domain/formatters/events/tenant.go
  pkg/domain/formatters/events/user.go
  pkg/domain/repositories/tenant_cluster_binding_repo.go
  pkg/domain/repositories/user_role_binding.go
  pkg/eventsourcing/messaging/bus_rabbitmq_config.go
  pkg/grpc/middleware/validator/cluster_test.go
  pkg/grpc/middleware/validator/validator_wrapper.go
  pkg/grpc/server.go
Labels: enhancement

#89 Revise Secret Management
  README.md
  docs/architecture-decisions/ADR-3-secret-management.md
  docs/concepts/data-model.md
Labels: documentation, chore

#98 Remove automaxprocs dependency
  internal/test/testenv.go
Labels: bug

#90 Add get user actions support for audit service
  api/domain/queryhandler_service.proto
  cmd/queryhandler/server.go
  go.mod
  internal/audit_log_test.go
  internal/queryhandler/audit_log_server.go
  internal/queryhandler/testenv.go
  pkg/api/domain/queryhandler_service.pb.go
  pkg/api/domain/queryhandler_service.pb.validate.go
  pkg/api/domain/queryhandler_service_grpc.pb.go
Labels: enhancement
