Repository finleap-connect/monoskope, pull requests merged in 2022-06, with the labels that each got.

#162 update rabbitmq chart to the latest available 8.x.x chart version
  build/package/helm/monoskope/Chart.yaml
Labels: bug

#164 auto-approve and auto-merge dependabot PRs
  .github/workflows/dependabot-auto-approve.yaml
  .github/workflows/dependabot-auto-merge.yaml
Labels: enhancement

#170 Fix go coverage
  .github/workflows/golang.yaml
  go.mk
Labels: bug

#171 Fix Broken SCIM integration
  build/package/helm/gateway/files/policies/policies.rego
  build/package/helm/gateway/files/policies/policies_test.rego
  internal/gateway/auth/auth_token_test.go
  internal/gateway/auth_server.go
  internal/gateway/testenv.go
  internal/scimserver/auth_handler.go
  internal/scimserver/server_test.go
  internal/scimserver/suite_test.go
Labels: bug

#173 Ignore deleted tenants on tenant users
  pkg/domain/queryhandler.go
  pkg/domain/repositories/tenant_user_repo.go
  pkg/domain/repositories/tenant_user_repo_test.go
Labels: bug

#180 Make ClusterBootstrapTokenCreated known again
  pkg/domain/constants/events/events.go
  pkg/domain/projectors/cluster.go
Labels: bug

#181 Cleanup data model by removing secrets
  docs/concepts/data-model.md
Labels: chore

#186 Readd handler for former events
  pkg/domain/aggregates/cluster.go
Labels: bug

#172 Fix audit log get by user returns some user actions
  hack/goget-wrapper
  internal/audit_log_test.go
  internal/gateway/testenv.go
  internal/integration_test.go
  internal/queryhandler/audit_log_server.go
  internal/testenv.go
  pkg/audit/formatters/audit/audit_formatter.go
  pkg/eventsourcing/repositories/in_memory.go
Labels: bug

#187 Fix roles/tenants/clusters values are missing from the audit log users overview
  internal/audit_log_test.go
  internal/queryhandler/audit_log_server.go
  internal/testenv.go
  pkg/audit/formatters/audit/audit_formatter.go
  pkg/audit/formatters/snapshotter.go
  pkg/audit/formatters/user_snapshotter.go
  pkg/domain/constants/formatters/formatters.go
  pkg/domain/formatters/events/certificate.go
  pkg/domain/formatters/events/cluster.go
  pkg/domain/formatters/events/tenant.go
  pkg/domain/formatters/events/user.go
  pkg/domain/formatters/overviews/user.go
Labels: bug
