Repository finleap-connect/monoskope, pull requests merged in 2022-04, with the labels that each got.

#117 TDR restructure events to improve aggregation
  docs/technical-decisions/TDR-01-restructure-events-to-improve-aggregation.md
Labels: chore

#129 Update dependabot settings
  .github/dependabot.yml
  .github/workflows/dependabot-merge.yml
Labels: bug

#127 Add get by user support to audit service
  api/domain/queryhandler_service.proto
  api/eventsourcing/eventstore_service.proto
  api/eventsourcing/messages.proto
  internal/audit_log_test.go
  internal/eventstore/api_server.go
  internal/eventstore/usecases/retrieve_events.go
  internal/queryhandler/audit_log_server.go
  pkg/api/domain/queryhandler_service.pb.go
  pkg/api/domain/queryhandler_service.pb.validate.go
  pkg/api/domain/queryhandler_service_grpc.pb.go
  pkg/api/eventsourcing/eventstore_service.pb.go
  pkg/api/eventsourcing/eventstore_service_grpc.pb.go
  pkg/api/eventsourcing/messages.pb.go
  pkg/api/eventsourcing/messages.pb.validate.go
  pkg/domain/constants/events/events.go
  pkg/domain/formatters/events/user.go
  pkg/eventsourcing/event_store.go
  pkg/eventsourcing/storage/store_postgres.go
  pkg/eventsourcing/storage/store_postgres_test.go
  test/api/eventsourcing/eventstore_client_mock.go
Labels: enhancement
