Repository finleap-connect/monoskope, pull requests merged in 2022-01, with the labels that each got.

#38 Reload certificates automatically
  go.mod
  go.sum
  pkg/eventsourcing/messaging/bus_rabbitmq_config.go
  pkg/eventsourcing/storage/store_postgres_config.go
  pkg/grpc/connection.go
  pkg/tls/suite_test.go
  pkg/tls/testenv.go
  pkg/tls/tls_config.go
  pkg/tls/tls_config_test.go
Labels: feature

#39 K8s auth token lifetime tied to roles
  build/package/helm/gateway/README.md
  build/package/helm/gateway/templates/config-k8s-auth.yaml
  build/package/helm/gateway/templates/deployment.yaml
  build/package/helm/gateway/values.yaml
  build/package/helm/monoskope/README.md
  build/package/helm/monoskope/templates/ambassador/ambassador-auth.yaml
  build/package/helm/scimserver/README.md
  cmd/gateway/root.go
  cmd/gateway/server.go
  docs/README.md
  go.mod
  go.sum
  internal/gateway/auth/client.go
  internal/gateway/auth/constants.go
  internal/gateway/auth_server.go
  internal/gateway/cluster_auth_server.go
  internal/gateway/cluster_auth_server_test.go
  internal/gateway/suite_test.go
  internal/gateway/usecases/get_auth_token.go
  internal/gateway/usecases/get_auth_token_test.go
  pkg/domain/errors/errors.go
  pkg/domain/metadata/metadata.go
Labels: feature, chore

#41 add whitespace trimming for user fields
  pkg/scim/user.go
  pkg/scim/user_test.go
Labels: bug
