Repository finleap-connect/monoskope, pull requests merged in 2022-02, with the labels that each got.

#45 Make RabbitEventBusConfig fields accessible
  CHANGELOG.md
  pkg/eventsourcing/messaging/bus_rabbitmq.go
  pkg/eventsourcing/messaging/bus_rabbitmq_config.go
Labels: chore

#47 API Token docs
  docs/deployment/04-configure-scim.md
  docs/operation/05-api-tokens.md
Labels: chore

#50 store_refresh_middleware seems to be buggy
  pkg/eventsourcing/eventhandler/store_refresh_middleware.go
Labels: bug

#51 Keep it simple and use mermaid rendering of github
  docs/diagrams/01-monoctl-authentication-flow.md
  docs/diagrams/01-monoctl-authentication-flow.mmd
  docs/diagrams/01-monoctl-authentication-flow.mmd.png
  docs/diagrams/02-monoctl-authentication-refresh-flow.md
  docs/diagrams/02-monoctl-authentication-refresh-flow.mmd
  docs/diagrams/02-monoctl-authentication-refresh-flow.mmd.png
Labels: chore

#52 Monoskope Setup Guide
  INSTALL.md
  MAINTAINERS.md
  docs/deployment/02-identity-provider-setup.md
  docs/deployment/README.md
Labels: chore

#65 Enhance issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/release-drafter.yml
Labels: enhancement, chore
