Repository finleap-connect/monoskope, pull requests merged in 2022-07, with the labels that each got.

#191 Clean up Makefile and use go install instead of self-made go get wrapper
  .gitignore
  Makefile
  go.mk
  hack/goget-wrapper
  hack/golangci-lint.sh
  tools/.gitkeep
Labels: chore

#194 Fix user role binding can't be recreated after deletion
  internal/integration_test.go
  pkg/domain/aggregates/user_role_binding.go
Labels: bug

#201 Fix cluster access is flaky
  cmd/gateway/server.go
  internal/commandhandler/testenv.go
  internal/eventstore/api_server.go
  internal/eventstore/metrics/event_store_metrics.go
  internal/gateway/auth_server_test.go
  internal/gateway/cluster_auth_server_test.go
  internal/gateway/suite_test.go
  internal/gateway/testenv.go
  internal/gateway/usecases/get_auth_token_test.go
  internal/queryhandler/audit_log_server.go
  internal/queryhandler/testenv.go
  internal/scimserver/server_test.go
  internal/scimserver/testenv.go
  internal/test/domain/repositories/repositories.go
  internal/testenv.go
  pkg/domain/aggregates/suite_test.go
  pkg/domain/commandhandler.go
  pkg/domain/formatters/overviews/user.go
  pkg/domain/gateway.go
  pkg/domain/mock/mock_data.go
  pkg/domain/projectors/cluster_test.go
  pkg/domain/projectors/tenant_cluster_binding_test.go
  pkg/domain/projectors/tenant_test.go
  pkg/domain/projectors/user_test.go
  pkg/domain/repositories/cluster_access_repo.go
  pkg/domain/repositories/domain_repo.go
  pkg/domain/repositories/remote_user_repo.go
  pkg/domain/repositories/tenant_user_repo.go
  pkg/domain/repositories/user_repo.go
  pkg/domain/repositories/user_role_binding.go
  test/audit/audit_log_test.go
  test/audit/suite_test.go
  test/integration/integration_test.go
  test/integration/suite_test.go
Labels: bug

#210 WIP: Use most recent Ambassador / Emissary-Ingress
  .gitignore
  build/package/helm/monoskope/Chart.lock
  build/package/helm/monoskope/Chart.yaml
  build/package/helm/monoskope/templates/_helpers.tpl
  build/package/helm/monoskope/templates/ambassador/ambassador-cert.yaml
  build/package/helm/monoskope/templates/ambassador/ambassador-host.yaml
  build/package/helm/monoskope/templates/ambassador/mappings/commandhandler.yaml
  build/package/helm/monoskope/templates/ambassador/mappings/gateway.yaml
  build/package/helm/monoskope/templates/ambassador/mappings/queryhandler.yaml
  build/package/helm/monoskope/templates/ambassador/mappings/scimserver.yaml
  build/package/helm/monoskope/values.yaml
Labels: enhancement

#211 Fix issues with recent Emissary-Ingress version
  build/package/helm/monoskope/values.yaml
Labels: bug
